# Generated by Django 5.0 on 2024-05-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='mobile',
            new_name='PhoneNumber',
        ),
    ]
