# Generated by Django 5.0 on 2024-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_rename_email_queries_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=56)),
                ('Password', models.CharField(max_length=56)),
            ],
        ),
    ]
