# Generated by Django 5.0 on 2024-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=56)),
                ('lastName', models.CharField(max_length=56)),
                ('email', models.CharField(max_length=56)),
                ('phone', models.CharField(default='+91', max_length=13)),
                ('disease', models.CharField(default='None', max_length=56)),
                ('treatment_start_date', models.CharField(default='2024-05-26', max_length=56)),
                ('treatment_end_date', models.CharField(default='2024-08-26', max_length=56)),
                ('doctor_assigned', models.CharField(default='None', max_length=56)),
                ('address', models.CharField(max_length=56)),
                ('password', models.CharField(max_length=56)),
                ('patientId', models.CharField(default=59469, max_length=56, unique=True)),
            ],
        ),
    ]
